name: Quarkus
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ['11' ]
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Test with Maven
        run: ./mvnw test